### ISSUE TITLE
没有权限是什么情况

### ISSUE THREAD

**Issue by xc1988** [linguo2625469/YangLeGeYang_web#2]
![image](https://user-images.githubusercontent.com/13324648/192078349-8bf003f3-e5ac-439d-b415-4892227c32a5.png)
显示没有权限

**Comment by Zq-000** [comment]
重新获取一下token

**Comment by linguo2625469** [comment]
token错误会提示没有权限

**Comment by xc1988** [comment]
> token错误会提示没有权限

用了好几个抓包的 抓出来都是这个token
